// src/renderer/src/pages/formData.js

export const initialFormData = {
  studentId: '',
  aadharNo: '',
  name: '',
  surname: '',
  fathersName: '',
  mothersName: '',
  religion: '',
  caste: '',
  subCaste: '',
  placeOfBirth: '',
  taluka: '',
  district: '',
  state: '',
  dateOfBirth: '',
  lastAttendedSchool: '',
  lastSchoolStandard: '',
  dateOfAdmission: '',
  admissionStandard: '',
  progress: '',
  conduct: '',
  dateOfLeaving: '',
  currentStandard: '',
  reasonOfLeaving: '',
  remarks: '',
  motherTongue: '',
  ten: '',
  grn: '',
  certGenCount: '0'
}
